### ISSUE TITLE
Plugin Layer Not working

### ISSUE THREAD

**Issue by boesiii** [amigocloud/qgis-amigocloud-plugin#3]
Hello,

I tried to use your plugin with my data but after I input my project ID, Dataset ID, and Token my data doesnot load.  There are no error boxes.

Is your plugin ready to be used?

Thanks
Ed

**Comment by vchernetsky** [comment]
Hi Ed,

The qgis plugin would require a latest version of gdal with amigocloud plugin. The source code is here: https://github.com/amigocloud/gdal . But it's not part of the GDAL package yet. We're working on integrating it into GDAL tree today.

Regards,
Victor

**Comment by rburhum** [comment]
Actually @boesiii , we just put the code on GDAL trunk yesterday. If you want to use it, you will need to compile the GDAL plugin. What version of QGIS and what OS are you currently using?

**Comment by boesiii** [comment]
I am using Qgis 2.12 on Windows 7 64 bit.

**Comment by rburhum** [comment]
OSGeo4W or another installer? The reason I want to know is to find out what
version of GDAL it ships with.

**Comment by boesiii** [comment]
I installed using the "standalone" installer (http://qgis.org/downloads/QGIS-OSGeo4W-2.12.0-1-Setup-x86_64.exe) and it came with GDAL 1.11.3

**Comment by boesiii** [comment]
I would rather not compile GDAL.  Would I be to use the AmigoCloud plugin if I installed the nightly version of Qgis?

**Comment by rburhum** [comment]
Only if it is using trunk since we just added the driver last week: https://github.com/OSGeo/gdal/commit/e3e6b25e093e296a2318558a45eaac470f368367

The other option is, if QGIS is using the 2.0 branch of GDAL, to compile it as a plugin. 

If you really want to try it, can we have a quick chat over Skype/Gmail to see if I can short-circuit the process? Contact me through: https://www.amigocloud.com/homepage/contact
